### ISSUE TITLE
Any plans for Android?

### ISSUE THREAD

**Issue by CheyenneForbes** [lukemiles/cordova-plugin-detect-screenshot#1]

**Comment by worm-emoji** [comment]
Not yet -- it's a bit more complicated because the internal storage has to be monitored for new screenshots as Android doesn't send out an event in the same way iOS does. 

PRs are appreciated, however. I'm closing this for now unless anyone has some code / insights to add.

**Comment by CheyenneForbes** [comment]
on android to make the plugin you could listen for ACTION_MEDIA_SCANNER_SCAN_FILE

**Comment by worm-emoji** [comment]
@CheyenneForbes would love a PR with this
