### ISSUE TITLE
Event UIApplicationUserWillTakeScreenshotNotification

### ISSUE THREAD

**Issue by fagnernostrum** [lukemiles/cordova-plugin-detect-screenshot#5]
I read that since IOS 8 there is the UIApplicationUserWillTakeScreenshotNotification event. Do you intend to add this event capture in this plug-in?

Thank you.

Reference: https://www.raywenderlich.com/48001/easily-overlooked-new-features-ios-7#screenshot

**Comment by worm-emoji** [comment]
That event doesn't exist. There currently is no way to detect when a user is about to take a screenshot, you can only account for it after the fact.

From the article you linked:

>**_Hopefully_** Apple adds an UIApplicationUserWillTakeScreenshotNotification in iOS 8!

Emphasis mine. Key word being "hopefully", they never added that event nor is there any official docs for it.
