### ISSUE TITLE
new function

### ISSUE THREAD

**Issue by fenglu09** [lukemiles/cordova-plugin-detect-screenshot#7]
Can this plugin return the imageURl or base64 data for the screenshot image?

**Comment by worm-emoji** [comment]
This plugin can only listen for screenshot events. iOS does not expose a way to fetch what was screenshotted, however, you could listen for a screenshot and use something like [cordova-screenshot](https://github.com/gitawego/cordova-screenshot) to get what's on the screen at the time. 

Closing for now as it's outside of the scope of this (tiny) plugin.
